services:
  db:
    image: postgres:15-alpine
    container_name: abc_project_database
    environment:
      POSTGRES_USER: abc_user
      POSTGRES_PASSWORD: abc_password
      POSTGRES_DB: abc_db
    volumes:
      - ./init-db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: abc_project_app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/abc_db
      SPRING_DATASOURCE_USERNAME: abc_user
      SPRING_DATASOURCE_PASSWORD: abc_password
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate